import { describe, it, expect, vi } from 'vitest';
import { parseAttachmentHandBinding, cloneAttachmentHandBinding } from './handBinding';
import { parseAttachmentConfig } from './configLoader';
import { parseAttachmentPlacementPreset, parseLive2DModelProfile } from './profileLoader';
import { createBlankCreatorDraft, cloneCreatorDraft, draftFromProjectPreset } from './creator/creatorDraft';
import { switchCreatorAdaptation } from './creator/creatorAdaptationSwitch';
import { adaptationState } from './creator/creatorAuthoringState';
import { registerCubism2HandRenderer } from './Cubism2HandRenderer';
import { profileForHandBinding } from './creator/creatorHandBinding';
import { isAttachmentSemanticAnchorId, attachmentSemanticAnchorMatchesPreset } from './semanticAnchorContract';

const anchors=[{index:0,weight:1,neutral:{x:0,y:0}},{index:1,weight:1,neutral:{x:2,y:0}},{index:2,weight:1,neutral:{x:0,y:2}}];
const binding=()=>parseAttachmentHandBinding({version:1,runtime:'cubism2',textureLayer:'front',transition:'weighted-scenes',unsupportedState:'hide-with-diagnostic',states:[{id:'old',displayName:'旧手型',drawableId:'mesh-old',anchors,contact:[{index:0,weight:.5},{index:1,weight:.5}],insertion:'before',mirrorX:false,rotationOffsetRad:0},{id:'new',displayName:'新手型',drawableId:'mesh-new',anchors,contact:[{index:0,weight:1}],insertion:'after',mirrorX:true,rotationOffsetRad:.3}]});
const placement={spriteAnchor:{x:.5,y:.5},offset:{x:0,y:0},rotationOffsetRad:0,localScale:1};
const preset=(hand=true)=>parseAttachmentPlacementPreset({schema:'webgal-live2d-attachment-preset',schemaVersion:2,presetId:'v2/hand-test',approvalStatus:'candidate',attachmentAssetId:'hand-test',modelProfileId:'model-test',anchorName:'hand-contact',fit:{scaleMode:'fixed'},placement,...(hand?{handBinding:binding()}:{})},'test://preset');
const profile=()=>parseLive2DModelProfile({schema:'webgal-live2d-model-profile',schemaVersion:1,profileVersion:1,modelProfileId:'model-test',characterId:'test',modelId:'test',modelPath:'game/figure/test/model.json',fingerprint:{modelJsonSha256:'a'.repeat(64),drawableCount:2},anchors:[{name:'hand-contact',anchorProfileId:'contact',drawableId:'mesh-old',vertexCount:3,points:anchors}]},'test://profile');

describe('optional hand state adaptation protocol',()=>{
  it('creates a new hand contact accepted by the normal script and preserves source Profile',()=>{const source=profile(),before=JSON.stringify(source),created=profileForHandBinding(source,binding());expect(isAttachmentSemanticAnchorId(created.anchorName)).toBe(true);expect(attachmentSemanticAnchorMatchesPreset(created.anchorName,created.anchorName)).toBe(true);expect(created.profile.anchors.some(a=>a.name===created.anchorName)).toBe(true);expect(created.profile.modelProfileId).toMatch(/^user-profile-[0-9a-f-]{36}$/);expect(JSON.stringify(source)).toBe(before);});
  it('legacy preset and config remain on the ordinary path',()=>{expect(preset(false).handBinding).toBeUndefined();expect(parseAttachmentConfig({schema:'webgal-live2d-attachment-v1',configId:'legacy',target:{modelPath:'game/figure/test/model.json',anchorProfile:{drawableId:'mesh-old',anchors}},fit:{scaleMode:'fixed'},layers:{front:'test.png'},placement},'test.json').handBinding).toBeUndefined();});
  it('restores all state contacts, direction and insertion data without aliasing',()=>{const p=preset(),draft=draftFromProjectPreset(p,{figureKey:'figure',figureGeneration:'g'}),copy=cloneCreatorDraft(draft);expect(copy.handBinding).toEqual(p.handBinding);copy.handBinding!.states[0].anchors[0].neutral.x=99;expect(draft.handBinding!.states[0].anchors[0].neutral.x).toBe(0);});
  it('restores the selected adaptation and removes hand config when switching to an ordinary one',()=>{const p=preset(),plain=preset(false),model=profile(),current={...createBlankCreatorDraft(),presetId:p.presetId,attachmentDefinitionId:p.attachmentAssetId,modelProfileId:p.modelProfileId,anchorName:p.anchorName,handBinding:binding()};const restored=switchCreatorAdaptation(current,[{preset:plain,modelProfile:model}],model).draft;expect(restored.handBinding).toBeUndefined();const restoredHand=switchCreatorAdaptation(restored,[{preset:p,modelProfile:model}],model).draft;expect(restoredHand.handBinding).toEqual(p.handBinding);});
  it('new target adaptation does not inherit another model hand binding',()=>{const current={...createBlankCreatorDraft(),handBinding:binding()},target=profile();expect(switchCreatorAdaptation(current,[],target,true).draft.handBinding).toBeUndefined();});
  it('marks adaptation dirty when only a hand direction changes',()=>{const draft={...createBlankCreatorDraft(),handBinding:binding()},before=adaptationState(draft);draft.handBinding.states[1].rotationOffsetRad=1;expect(adaptationState(draft)).not.toBe(before);});
  it.each(['bad-weight','bad-index','duplicate-state','bad-mirror','nan-angle'])('rejects malformed %s rather than silently dropping configuration',kind=>{const b=binding() as any;if(kind==='bad-weight')b.states[0].contact[0].weight=5;if(kind==='bad-index')b.states[0].contact[0].index=99;if(kind==='duplicate-state')b.states[1].id=b.states[0].id;if(kind==='bad-mirror')b.states[0].mirrorX='false';if(kind==='nan-angle')b.states[0].rotationOffsetRad=NaN;expect(()=>parseAttachmentHandBinding(b)).toThrow('HAND_BINDING_INVALID');});
  it('keeps independent cloned contact records',()=>{const b=binding(),copy=cloneAttachmentHandBinding(b);copy.states[0].contact[0].weight=0;expect(b.states[0].contact[0].weight).toBe(.5);});
});

describe('production Cubism2 adapter ownership',()=>{
  function setup(){const inserted=vi.fn(),drawables=[{getDrawDataID:()=>({id:'mesh-old'}),draw:vi.fn(),_$6s:{}},{getDrawDataID:()=>({id:'mesh-new'}),draw:vi.fn()}],dp={textures:['base','foreign'] as unknown[],_$Uo:inserted,getClipBufPre_clipContextDraw:()=>null,setClipBufPre_clipContextForDraw:vi.fn(),_$WP:vi.fn(),culling:false},core={getModelContext:()=>({getDrawData:(i:number)=>drawables[i],_$Ws:[],_$Er:[]}),getDrawParam:()=>dp,setTexture:vi.fn((slot:number,texture:unknown)=>{dp.textures[slot]=texture;})};
    const internal={coreModel:core,settings:{textures:['base']},draw:vi.fn((_gl?:unknown)=>drawables.forEach(d=>d.draw()))},original=internal.draw,gl={},renderer={gl,CONTEXT_UID:1,texture:{bind:vi.fn()}},texture={baseTexture:{_glTextures:{1:{texture:{}}}}},p={id:'mesh-old',insertion:'before' as const,weight:1,quad:new Float32Array(8),texture:texture as never,opacity:.4};
    return {inserted,drawables,dp,internal,original,gl,owner:{renderer:renderer as never,presentations:()=>[p],fail:vi.fn()}};}
  it('inserts only in actual model draw and restores original methods on final owner release',()=>{const s=setup(),draw=s.drawables[0].draw,release=registerCubism2HandRenderer({internalModel:s.internal} as never,s.owner);s.drawables[0].draw();expect(s.inserted).not.toHaveBeenCalled();s.internal.draw(s.gl as never);expect(s.inserted).toHaveBeenCalledTimes(1);expect(s.inserted.mock.calls[0][5]).toBe(.4);expect(s.dp.textures).toEqual(['base','foreign']);release();expect(s.internal.draw).toBe(s.original);expect(s.drawables[0].draw).toBe(draw);});
  it('one owner removal does not uninstall another owner or revive removed presentations',()=>{const s=setup(),second={...s.owner,presentations:()=>[]},a=registerCubism2HandRenderer({internalModel:s.internal} as never,s.owner),b=registerCubism2HandRenderer({internalModel:s.internal} as never,second);a();s.internal.draw(s.gl as never);expect(s.inserted).not.toHaveBeenCalled();b();expect(s.internal.draw).toBe(s.original);});
});
