import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {test} from 'node:test';
import {fixture,payload,mutateDocument,snapshot,put} from './creator-fixtures.mjs';
import {createCreatorStore} from '../runtime/creator-store.mjs';
import {migrateBuiltinPackages} from '../runtime/builtin-migration.mjs';
import {creatorScenePath} from '../runtime/creator-scene-name.mjs';
const leaf='anon-straw-hat-both-v1',oldId='v2/'+leaf,newId='v2/straw-hat-both-v1',rel='game/attachments-v2/portable/';
function saved(){const f=fixture(),store=createCreatorStore(f.options),a=payload({leaf,both:true}),r=store.saveToGame(a);store.saveToGame({...payload({leaf,both:true,profileId:'profile-b'}),expectedRevision:r.revision});return {...f,store,a};}
test('neutral migration preserves both adaptations/images, old script alias and catalog identity; second run no-op',()=>{const f=saved();try{
 const before=JSON.parse(fs.readFileSync(path.join(f.project,rel+leaf+'/attachment.json'))),sceneBefore=snapshot(path.join(f.project,'game/scene'));
 const result=migrateBuiltinPackages(f.project);assert.equal(result.status,'MIGRATED');assert.ok(fs.existsSync(result.backup));
 const loaded=f.store.loadAttachment({projectName:'测试 Demo',presetId:oldId});assert.equal(loaded.presetId,newId);assert.equal(loaded.integrity,'HASH_VALIDATED');assert.equal(loaded.packageDocument.adaptations.length,2);
 for(let i=0;i<2;i++){assert.deepEqual(loaded.packageDocument.adaptations[i].modelProfile,before.adaptations[i].modelProfile);assert.deepEqual(loaded.packageDocument.adaptations[i].preset.placement,before.adaptations[i].preset.placement);}
 const alias=JSON.parse(fs.readFileSync(path.join(f.project,rel+leaf+'/attachment.json')));assert.equal(alias.adaptations[0].preset.presetId,oldId);assert.equal(alias.asset.layers.front,loaded.packageDocument.asset.layers.front);assert.deepEqual(fs.readdirSync(path.join(f.project,rel+leaf)),['attachment.json']);
 assert.deepEqual(snapshot(path.join(f.project,'game/scene')),sceneBefore);assert.deepEqual(f.store.context().savedAttachments.map(x=>x.presetId),[newId]);
 const all=snapshot(f.project);assert.equal(migrateBuiltinPackages(f.project).status,'NO_OP');assert.deepEqual(snapshot(f.project),all);
 const updated=mutateDocument(payload({leaf:'straw-hat-both-v1',both:true}),d=>d.adaptations[0].preset.placement.offset.x=88);
 f.store.saveToGame({...updated,expectedRevision:loaded.revision});const newAlias=JSON.parse(fs.readFileSync(path.join(f.project,rel+leaf+'/attachment.json')));assert.equal(newAlias.adaptations[0].preset.placement.offset.x,88);assert.equal(newAlias.adaptations.length,2);
}finally{f.store.close();}});
for(const mode of ['target','edited','missing-owner'])test('migration preflight rejects '+mode+' with zero writes',()=>{const f=saved();try{
 if(mode==='target')fs.mkdirSync(path.join(f.project,rel+'straw-hat-both-v1'));if(mode==='edited')fs.appendFileSync(path.join(f.project,rel+leaf+'/attachment.json'),' ');if(mode==='missing-owner')fs.renameSync(path.join(f.project,'game/attachments-v2/.webgal-attachment-creator/game-save-v2.json'),path.join(f.project,'old-owner.json'));
 const before=snapshot(f.project);assert.throws(()=>migrateBuiltinPackages(f.project),/CREATOR_IDENTITY_/);assert.deepEqual(snapshot(f.project),before);
}finally{f.store.close();}});
for(const stage of ['installed','ledger'])test('migration rollback restores active files after '+stage,()=>{const f=saved();try{const before=snapshot(f.project);assert.throws(()=>migrateBuiltinPackages(f.project,{fault(s){if(s===stage)throw Error('INJECTED');}}),/INJECTED/);const after=snapshot(f.project);for(const [p,h]of Object.entries(before))assert.equal(after[p],h,p);assert.equal(Object.keys(after).filter(p=>p.startsWith(rel+'straw-hat')).length,0);assert.equal(fs.existsSync(path.join(f.project,'game/attachments-v2/.builtin-identity-migration.json')),false);}finally{f.store.close();}});
test('scene names are readable, stable after rename, safe and different for same display name',()=>{const first=creatorScenePath(newId,'草帽'),other=creatorScenePath('v2/other','草帽');assert.match(first,/附件测试-草帽-[a-f0-9]{8}\.txt$/);assert.notEqual(first,other);assert.equal(creatorScenePath(newId,'改名',[first]),first);assert.ok(!creatorScenePath(newId,'../../\\bad').includes('..'));});
test('neutral factory shortcut reads user legacy placement without rewriting source or character identity',()=>{const f=fixture(),root=f.authoring+'/workspace';put(root+'/game/config.txt','Game_name:Local;');put(root+'/game/scene/start.txt','original');const source={presetId:oldId,modelProfileId:'anon-real-profile',placement:{offset:{x:19,y:73}}};put(f.authoring+'/library/placement-presets/'+leaf+'.json',JSON.stringify(source));const store=createCreatorStore({...f.options,authorizedAuthoringWorkspaceRoot:root});try{const before=snapshot(f.authoring),bytes=store.readAuthoringResource('game/attachments-v2/presets/straw-hat-both-v1.json'),p=JSON.parse(bytes);assert.equal(p.presetId,newId);assert.equal(p.modelProfileId,source.modelProfileId);assert.deepEqual(p.placement,source.placement);assert.deepEqual(snapshot(f.authoring),before);}finally{store.close();}});
test('late foreign destination remains in place and original package rolls back',()=>{const f=saved();try{const before=fs.readFileSync(path.join(f.project,rel+leaf+'/attachment.json')),foreign=path.join(f.project,rel+'straw-hat-both-v1/foreign.txt');assert.throws(()=>migrateBuiltinPackages(f.project,{fault(stage){if(stage==='after-old-moved'){fs.mkdirSync(path.dirname(foreign));fs.writeFileSync(foreign,'foreign');}}}),/CREATOR_IDENTITY_TARGET_CONFLICT/);assert.equal(fs.readFileSync(foreign,'utf8'),'foreign');assert.ok(fs.readFileSync(path.join(f.project,rel+leaf+'/attachment.json')).equals(before));}finally{f.store.close();}});
for(const where of ['original-path','new-content'])test('concurrent '+where+' preserved with recovery journal and backup',()=>{const f=saved();try{const foreign=path.join(f.project,rel+(where==='original-path'?leaf:'straw-hat-both-v1')+'/foreign.txt');assert.throws(()=>migrateBuiltinPackages(f.project,{fault(stage){if(stage===(where==='original-path'?'after-old-moved':'installed')){fs.mkdirSync(path.dirname(foreign),{recursive:true});fs.writeFileSync(foreign,'foreign');throw Error('INTERRUPTED');}}}),/CREATOR_IDENTITY_RECOVERY_REQUIRED/);assert.equal(fs.readFileSync(foreign,'utf8'),'foreign');const j=JSON.parse(fs.readFileSync(path.join(f.project,'game/attachments-v2/.builtin-identity-migration.json')));assert.ok(fs.existsSync(path.join(j.backup,leaf,'attachment.json')));assert.throws(()=>migrateBuiltinPackages(f.project),/CREATOR_IDENTITY_RECOVERY_REQUIRED/);}finally{f.store.close();}});
test('pending identity recovery blocks save and external-edit acceptance without any writes',()=>{const f=saved();try{fs.writeFileSync(path.join(f.project,'game/attachments-v2/.builtin-identity-migration.json'),'{}');const before=snapshot(f.project);assert.throws(()=>f.store.saveToGame(f.a),/CREATOR_IDENTITY_RECOVERY_REQUIRED/);assert.throws(()=>f.store.acceptAttachmentChanges(f.a),/CREATOR_IDENTITY_RECOVERY_REQUIRED/);assert.deepEqual(snapshot(f.project),before);}finally{f.store.close();}});
