import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {test} from 'node:test';
import {fixture,payload,mutateDocument,put,snapshot} from './creator-fixtures.mjs';
import {createCreatorStore} from '../runtime/creator-store.mjs';
import {createCreatorService} from '../runtime/creator-service.mjs';
function local(hooks={}){const f=fixture(),root=path.join(f.authoring,'workspace');put(root+'/game/config.txt','Game_name:Local;');put(root+'/game/scene/start.txt','original');const options={...f.options,authorizedAuthoringWorkspaceRoot:root};return {...f,root,options,store:createCreatorStore(options,hooks)};}
test('no model in workspace and no selected/authorized games: local save, reopen, merge, no scene or game writes',()=>{
 const f=local(),before=snapshot(f.data),a={...payload(),expectedRevision:null};f.options.projectGrants=[];const store=createCreatorStore(f.options);
 try{const r=store.saveAuthoringAttachment(a);assert.equal(r.exampleScene,'');assert.equal(r.savedLocally,true);assert.deepEqual(snapshot(f.data),before);assert.deepEqual(fs.readdirSync(f.root+'/game/scene'),['start.txt']);
 const second={...payload({profileId:'profile-b'}),expectedRevision:r.revision};const two=store.saveAuthoringAttachment(second);const loaded=store.loadAuthoringAttachment({presetId:a.presetId});assert.deepEqual(loaded.packageDocument.adaptations.map(x=>x.modelProfile.modelProfileId),['profile-a','profile-b']);assert.equal(loaded.projectName,'authoring-workspace');assert.equal(store.context().targetProjects.length,0);assert.equal(store.context().authoringWorkspace.savedAttachments.length,1);assert.equal(store.saveAuthoringAttachment({...second,expectedRevision:two.revision}).noOp,true);
 }finally{store.close();f.store.close();}
});
test('missing target model blocks game deployment only; body cannot request save-only bypass',()=>{const f=local(),before=snapshot(f.data);try{const a=payload({modelPath:'game/figure/missing/model.json'});f.store.saveAuthoringAttachment({...a,expectedRevision:null});assert.throws(()=>f.store.saveToGame({...a,saveOnly:true}),/CREATOR_TARGET_MODEL_MISSING/);assert.deepEqual(snapshot(f.data),before);}finally{f.store.close();}});
test('deployment to two games preserves local attachment and original scenes',()=>{const f=local();f.store.close();f.options.projectGrants.push({name:'Other',access:'attachment-write'});const store=createCreatorStore(f.options);try{const a=payload();store.saveAuthoringAttachment({...a,expectedRevision:null});const before=snapshot(f.root);for(const name of ['测试 Demo','Other'])store.saveToGame({...a,projectName:name});assert.deepEqual(snapshot(f.root),before);assert.equal(fs.readFileSync(f.project+'/game/scene/start.txt','utf8'),'用户原剧情不变;');assert.equal(fs.readFileSync(f.other+'/game/scene/start.txt','utf8'),'用户原剧情不变;');}finally{store.close();}});
test('local external edits require acceptance, preserve edits, then safely save; stale revisions reject',()=>{const f=local();try{const a=payload(),r=f.store.saveAuthoringAttachment({...a,expectedRevision:null}),file=f.root+'/game/attachments-v2/portable/test-hat/attachment.json';const d=JSON.parse(fs.readFileSync(file));d.adaptations[0].preset.placement.offset.x=77;fs.writeFileSync(file,JSON.stringify(d));const changed=f.store.loadAuthoringAttachment(a);assert.equal(changed.integrity,'USER_EDITED_REVIEW_REQUIRED');const accepted=f.store.acceptAuthoringAttachmentChanges({...a,expectedRevision:changed.revision});assert.equal(accepted.contentOverwritten,false);assert.equal(accepted.packageDocument.adaptations[0].preset.placement.offset.x,77);assert.throws(()=>f.store.saveAuthoringAttachment({...a,expectedRevision:r.revision}),/CREATOR_STALE/);const updated=mutateDocument(a,x=>x.adaptations[0].preset.placement.offset.x=88);f.store.saveAuthoringAttachment({...updated,expectedRevision:accepted.revision});assert.equal(f.store.loadAuthoringAttachment(a).packageDocument.adaptations[0].preset.placement.offset.x,88);}finally{f.store.close();}});
test('local interrupted transaction rolls back without changing games',()=>{let inject=false;const f=local({fault(stage){if(inject&&stage==='installed')throw Error('INJECTED');}});try{const a=payload(),r=f.store.saveAuthoringAttachment({...a,expectedRevision:null}),before=snapshot(f.root),games=snapshot(f.data);inject=true;assert.throws(()=>f.store.saveAuthoringAttachment({...mutateDocument(a,d=>d.displayName='changed'),expectedRevision:r.revision}));assert.deepEqual(snapshot(f.root),before);assert.deepEqual(snapshot(f.data),games);}finally{f.store.close();}});
test('authenticated HTTP local save/load routes require no game and close their service',async()=>{const f=local(),service=createCreatorService(f.options);try{const {origin,token}=await service.listen(0);const call=async(endpoint,body)=>{const r=await fetch(origin+endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Creator-Session':token},body:JSON.stringify(body)});assert.equal(r.status,200);return r.json();};const a=payload();const saved=await call('/__creator/save-local',{...a,expectedRevision:null});assert.equal(saved.projectName,'authoring-workspace');const loaded=await call('/__creator/load-local',{presetId:a.presetId,projectName:'Other'});assert.equal(loaded.presetId,a.presetId);assert.equal(loaded.integrity,'HASH_VALIDATED');}finally{await service.close();f.store.close();}});
