import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import test from 'node:test';import {createHash} from 'node:crypto';
import {resolveHostCompatibilityPlan,verifyInstalledHostCompatibility} from '../runtime/host-compatibility.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex').toUpperCase();
const root=path.resolve(import.meta.dirname,'../../evidence/compatibility-fixtures');fs.mkdirSync(root,{recursive:true});
const fact=(p,role)=>({path:p,role,bytes:1,sha256:hash('a')});
function fixture(){const host=fs.mkdtempSync(path.join(root,'case-'));for(const p of ['reference','dependency','managed','new'])fs.writeFileSync(path.join(host,p),'a');
const adapter={id:'verified-adapter',fingerprintSha256:hash('identity'),compatibilityVersion:1,baseFileCount:3,baseFiles:[fact('reference','REFERENCE_ONLY'),fact('dependency','DEPENDENCY_READONLY'),fact('managed','MANAGED_TRANSFORM_TARGET')],operations:['managed','new'].map(p=>({path:p,role:p==='new'?'PLUGIN_OWNED_NEW':'MANAGED_TRANSFORM_TARGET',action:'write',payloadPath:`payload/${p}`,postBytes:1,postSha256:hash('a')}))};
const state={hostAdapterId:adapter.id,hostFingerprintSha256:adapter.fingerprintSha256,hostFiles:adapter.operations.map(op=>({path:op.path,action:op.action,postimage:{exists:true,bytes:1,sha256:hash('a')}}))};return{host,adapter,state};}
test('reference changes/deletion and foreign files never become ownership drift',()=>{const f=fixture();fs.writeFileSync(path.join(f.host,'reference'),'user');fs.writeFileSync(path.join(f.host,'foreign'),'user');verifyInstalledHostCompatibility(f.host,f.adapter,f.state);fs.unlinkSync(path.join(f.host,'reference'));verifyInstalledHostCompatibility(f.host,f.adapter,f.state);});
test('dependency and managed conflicts aggregate without any writes',()=>{const f=fixture();for(const p of ['dependency','managed'])fs.writeFileSync(path.join(f.host,p),'user');assert.throws(()=>verifyInstalledHostCompatibility(f.host,f.adapter,f.state),e=>e.diagnostics.length===2&&e.diagnostics.some(x=>x.code==='HOST_DEPENDENCY_INCOMPATIBLE')&&e.diagnostics.some(x=>x.code==='OWNED_FILE_DRIFT'));for(const p of ['dependency','managed'])assert.equal(fs.readFileSync(path.join(f.host,p),'utf8'),'user');});
test('whole adapter identity and duplicate state cannot be mixed',()=>{const f=fixture();assert.throws(()=>verifyInstalledHostCompatibility(f.host,f.adapter,{...f.state,hostAdapterId:'another'}),/MISMATCH/);assert.throws(()=>verifyInstalledHostCompatibility(f.host,f.adapter,{...f.state,hostFiles:[...f.state.hostFiles,f.state.hostFiles[0]]}),/MISMATCH/);});
test('invalid roles actions payloads and postimages fail closed',()=>{for(const mutate of [a=>a.baseFiles[0].role='MANAGED_TRANSFORM_TARGET',a=>a.operations[0].action='unknown',a=>a.operations[0].payloadPath='../escape',a=>a.operations[0].postBytes=-1,a=>a.operations[1].role='REFERENCE_ONLY']){const f=fixture();mutate(f.adapter);assert.throws(()=>resolveHostCompatibilityPlan(f.adapter),/HOST_ADAPTER/);}});
