import * as fs from 'fs/promises';
import * as path from 'path';
import { createHash } from 'crypto';

const active = new Set<string>();

async function treeRevision(root: string): Promise<string> {
  const digest = createHash('sha256');
  async function visit(directory: string) {
    for (const name of (await fs.readdir(directory)).sort()) {
      const file = path.join(directory, name), stat = await fs.lstat(file);
      if (stat.isSymbolicLink()) throw new Error('WEB_EXPORT_LINK_UNSUPPORTED');
      digest.update(JSON.stringify([path.relative(root, file), stat.isDirectory()]));
      if (stat.isDirectory()) await visit(file);
      else digest.update(await fs.readFile(file));
    }
  }
  await visit(root);
  return digest.digest('hex');
}

export async function copyWebExportTree(source: string, target: string): Promise<void> {
  await fs.cp(source, target, {
    recursive: true,
    filter: async entry => {
      if ((await fs.lstat(entry)).isSymbolicLink()) throw new Error('WEB_EXPORT_LINK_UNSUPPORTED');
      return true;
    },
  });
}

/** Build in a sibling directory; a failed copy must never replace the last export. */
export async function commitWebExport(
  target: string,
  prepare: (stage: string) => Promise<void>,
  cleanupWarning: (message: string) => void,
): Promise<void> {
  target = path.resolve(target);
  const key = target.toLowerCase();
  if (active.has(key)) throw new Error('WEB_EXPORT_BUSY');
  active.add(key);
  let stage: string | undefined;
  let backup: string | undefined;
  let oldMoved = false;
  let committed = false;
  try {
    let original;
    try { original = await fs.lstat(target); } catch (e) { if (e.code !== 'ENOENT') throw e; }
    if (original && (!original.isDirectory() || original.isSymbolicLink()))
      throw new Error('WEB_EXPORT_TARGET_NOT_DIRECTORY');
    await fs.mkdir(path.dirname(target), { recursive: true });
    stage = await fs.mkdtemp(path.join(path.dirname(target), '.web-export-'));
    backup = stage + '-previous';
    // Preserve unrelated files in an existing export. Refuse links rather than
    // following them and accidentally writing outside this owned staging tree.
    const revision = original ? await treeRevision(target) : undefined;
    if (original) await copyWebExportTree(target, stage);
    await prepare(stage);
    let current;
    try { current = await fs.lstat(target); } catch (e) { if (e.code !== 'ENOENT') throw e; }
    if (Boolean(current) !== Boolean(original) || (current &&
      (current.dev !== original.dev || current.ino !== original.ino || current.isSymbolicLink())))
      throw new Error('WEB_EXPORT_TARGET_CHANGED');
    if (original && await treeRevision(target) !== revision)
      throw new Error('WEB_EXPORT_TARGET_CHANGED');
    if (original) { await fs.rename(target, backup); oldMoved = true; }
    try { await fs.rename(stage, target); committed = true; }
    catch (error) {
      if (oldMoved) {
        try { await fs.rename(backup, target); oldMoved = false; }
        catch (restoreError) {
          throw new Error(`WEB_EXPORT_RESTORE_REQUIRED: previous export retained at ${backup}; ${String(restoreError)}`);
        }
      }
      throw error;
    }
    if (oldMoved) {
      try { await fs.rm(backup, { recursive: true }); oldMoved = false; }
      catch (e) { cleanupWarning(`Web export committed; previous export retained at ${backup}: ${String(e)}`); }
    }
  } finally {
    // stage is generated by mkdtemp in the target parent, never a user path.
    if (stage && !committed) await fs.rm(stage, { recursive: true, force: true }).catch(e => cleanupWarning(String(e)));
    active.delete(key);
  }
}
